import dbConnect from "@/lib/mongodb"
import Booking from "@/models/Booking"
import { z } from "zod"
import { sendMail } from "@/lib/mail"

// GET - Fetch all bookings with optional filtering
export async function GET(req: Request) {
  if (!process.env.MONGODB_URI) {
    return Response.json({ error: "Database not configured" }, { status: 503 })
  }
  
  try {
    await dbConnect()
    
    // Get query parameters
    const { searchParams } = new URL(req.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '10')
    const status = searchParams.get('status')
    const email = searchParams.get('email')
    const search = searchParams.get('search')
    
    // Build query
    let query: any = {}
    
    if (status) query.status = status
    if (email) query.email = email
    if (search) {
      query.$or = [
        { firstName: { $regex: search, $options: 'i' } },
        { lastName: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { residence: { $regex: search, $options: 'i' } }
      ]
    }
    
    // Calculate pagination
    const skip = (page - 1) * limit
    
    // Execute queries
    const [bookings, total] = await Promise.all([
      Booking.find(query)
        .select("_id firstName lastName email phone residence departureDate returnDate travelers budget comments products status statusUpdatedAt createdAt")
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Booking.countDocuments(query)
    ])
    
    const totalPages = Math.ceil(total / limit)
    
    return Response.json({
      success: true,
      data: bookings,
      pagination: {
        page,
        limit,
        total,
        totalPages,
        hasNext: page < totalPages,
        hasPrev: page > 1
      }
    })
    
  } catch (error) {
    console.error('Failed to fetch bookings:', error)
    return Response.json({ error: "Failed to fetch bookings" }, { status: 500 })
  }
}

// POST - Create new booking
export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}))
  
  const schema = z.object({
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    email: z.string().email(),
    phone: z.string().min(3),
    residence: z.string().optional().default(""),
    departureDate: z.coerce.date().optional(),
    returnDate: z.coerce.date().optional(),
    travelers: z.coerce.number().int().min(1).default(1),
    budget: z.string().optional().default(""),
    comments: z.string().optional().default(""),
    products: z.array(z.object({ name: z.string(), price: z.number().optional() })).optional().default([]),
  })
  
  const parsed = schema.safeParse(body)
  if (!parsed.success) {
    return Response.json(
      { error: "Invalid input", details: parsed.error.flatten() },
      { status: 400 }
    )
  }

  // Try sending email first; do not fail request if it errors
  try {
    const recipients = (process.env.NOTIFY_EMAILS || "maseemmy2000@gmail.com,gihomart@250gmail.com").split(",").map(s => s.trim()).filter(Boolean)
    const d = parsed.data
    const fullName = `${d.firstName} ${d.lastName}`.trim()
    const html = `
      <h2>New Booking Request</h2>
      <p><strong>Name:</strong> ${fullName}</p>
      <p><strong>Email:</strong> <a href="mailto:${d.email}">${d.email}</a></p>
      <p><strong>Phone:</strong> ${d.phone}</p>
      ${d.residence ? `<p><strong>Residence:</strong> ${d.residence}</p>` : ""}
      ${d.departureDate ? `<p><strong>Departure:</strong> ${new Date(d.departureDate).toLocaleDateString()}</p>` : ""}
      ${d.returnDate ? `<p><strong>Return:</strong> ${new Date(d.returnDate).toLocaleDateString()}</p>` : ""}
      <p><strong>Travelers:</strong> ${d.travelers}</p>
      ${d.budget ? `<p><strong>Budget:</strong> ${d.budget}</p>` : ""}
      ${d.products && d.products.length ? `<p><strong>Selected Products/Programs:</strong><ul>${d.products.map((p:any) => `<li>${p.name}${p.price ? ` ($${p.price})` : ''}</li>`).join('')}</ul></p>` : ""}
      ${d.comments ? `<p><strong>Comments:</strong> ${d.comments.replace(/\n/g, "<br/>")}</p>` : ""}
      <p style="color:#888;font-size:12px;">This email was generated by the website. <br/>To reply to the client, simply reply to this email or click the email address above.</p>
    `
    await sendMail({ to: recipients, subject: `Booking request from ${fullName}`, html })

    // Confirmation email to customer
    const confirmHtml = `
      <h2>Thanks for your booking request</h2>
      <p>Hi ${fullName},</p>
      <p>We received your booking request and will contact you shortly.</p>
      ${d.residence ? `<p><strong>Residence:</strong> ${d.residence}</p>` : ""}
      ${d.departureDate ? `<p><strong>Departure:</strong> ${new Date(d.departureDate).toLocaleDateString()}</p>` : ""}
      ${d.returnDate ? `<p><strong>Return:</strong> ${new Date(d.returnDate).toLocaleDateString()}</p>` : ""}
      <p><strong>Travelers:</strong> ${d.travelers}</p>
      ${d.comments ? `<p><strong>Comments:</strong> ${d.comments.replace(/\n/g, "<br/>")}</p>` : ""}
      <p style="color:#888;font-size:12px;">This is a confirmation of your submission.</p>
    `
    await sendMail({ to: d.email, subject: "We received your booking request", html: confirmHtml })
  } catch (e) {
    console.error('Email sending failed:', e)
    // ignore email errors
  }

  // Try DB write; do not fail request if it errors
  try {
    await dbConnect()
    await Booking.create(parsed.data)
  } catch (e) {
    console.error('Database write failed:', e)
    // ignore db errors
  }

  return Response.json({ success: true }, { status: 201 })
}

// PUT - Update booking status (approve, waiting, reject)
export async function PUT(req: Request) {
  if (!process.env.MONGODB_URI) {
    return Response.json({ error: "Database not configured" }, { status: 503 })
  }

  const body = await req.json().catch(() => ({}))
  
  const schema = z.object({
    id: z.string().min(1, "Booking ID is required"),
    status: z.enum(['approved', 'waiting', 'rejected', 'pending']),
    adminComments: z.string().optional().default("")
  })
  
  const parsed = schema.safeParse(body)
  if (!parsed.success) {
    return Response.json(
      { error: "Invalid input", details: parsed.error.flatten() },
      { status: 400 }
    )
  }

  try {
    await dbConnect()
    
    const { id, status, adminComments } = parsed.data
    
    // Find and update booking
    const booking = await Booking.findByIdAndUpdate(
      id,
      { 
        status, 
        statusUpdatedAt: new Date() 
      },
      { new: true }
    )
    
    if (!booking) {
      return Response.json({ error: "Booking not found" }, { status: 404 })
    }

    // Send status update email to customer
    try {
      const fullName = `${booking.firstName} ${booking.lastName}`.trim()
      let subject = ''
      let html = ''

      switch (status) {
        case 'approved':
          subject = 'Your Booking Has Been Approved!'
          html = `
            <h2>Booking Approved!</h2>
            <p>Dear ${fullName},</p>
            <p>Great news! Your booking has been approved.</p>
            <p>We're excited to help you with your travel plans!</p>
            ${adminComments ? `<p><strong>Additional comments:</strong> ${adminComments}</p>` : ""}
            <br>
            <p>Best regards,<br>Your Travel Team</p>
          `
          break
        case 'waiting':
          subject = 'Your Booking Status Update'
          html = `
            <h2>Booking Status Update</h2>
            <p>Dear ${fullName},</p>
            <p>Your booking has been placed on the waiting list.</p>
            <p>We'll notify you as soon as spots become available.</p>
            ${adminComments ? `<p><strong>Additional comments:</strong> ${adminComments}</p>` : ""}
            <br>
            <p>Best regards,<br>Your Travel Team</p>
          `
          break
        case 'rejected':
          subject = 'Update on Your Booking Request'
          html = `
            <h2>Booking Update</h2>
            <p>Dear ${fullName},</p>
            <p>Unfortunately, your booking could not be processed at this time.</p>
            ${adminComments ? `<p><strong>Reason:</strong> ${adminComments}</p>` : ""}
            <br>
            <p>Best regards,<br>Your Travel Team</p>
          `
          break
        default:
          subject = 'Booking Status Update'
          html = `
            <h2>Booking Status Update</h2>
            <p>Dear ${fullName},</p>
            <p>Your booking status has been updated to: ${status}</p>
            ${adminComments ? `<p><strong>Comments:</strong> ${adminComments}</p>` : ""}
            <br>
            <p>Best regards,<br>Your Travel Team</p>
          `
      }

      await sendMail({ 
        to: booking.email, 
        subject, 
        html 
      })

    } catch (emailError) {
      console.error('Status update email failed:', emailError)
      // Continue even if email fails
    }

    return Response.json({ 
      success: true, 
      message: `Booking ${status} successfully`,
      data: booking 
    })
    
  } catch (error) {
    console.error('Failed to update booking:', error)
    return Response.json({ error: "Failed to update booking" }, { status: 500 })
  }
}

// DELETE - Remove booking
export async function DELETE(req: Request) {
  if (!process.env.MONGODB_URI) {
    return Response.json({ error: "Database not configured" }, { status: 503 })
  }

  const { searchParams } = new URL(req.url)
  const id = searchParams.get('id')
  
  if (!id) {
    return Response.json({ error: "Booking ID is required" }, { status: 400 })
  }

  try {
    await dbConnect()
    
    const booking = await Booking.findByIdAndDelete(id)
    
    if (!booking) {
      return Response.json({ error: "Booking not found" }, { status: 404 })
    }

    return Response.json({ 
      success: true, 
      message: "Booking deleted successfully" 
    })
    
  } catch (error) {
    console.error('Failed to delete booking:', error)
    return Response.json({ error: "Failed to delete booking" }, { status: 500 })
  }
}