import { NextApiRequest, NextApiResponse } from "next"
import dbConnect from "@/lib/mongodb"
import Booking from "@/models/Booking"
import { sendMail } from "@/lib/mail"

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" })
  }
  await dbConnect()
  const {
    firstName,
    lastName,
    email,
    phone,
    residence,
    departureDate,
    returnDate,
    travelers,
    budget,
    comments,
    products = [],
  } = req.body

  try {
    // Save booking to DB
    const booking = await Booking.create({
      firstName,
      lastName,
      email,
      phone,
      residence,
      departureDate,
      returnDate,
      travelers,
      budget,
      comments,
      products,
    })

  // Send notification email to both admins
  const adminEmails = ["maseemmy2000@gmail.com", "gihomart250@gmail.com"];
  const fullName = `${firstName} ${lastName}`.trim()
  const html = `
      <h2>New Booking Request</h2>
      <p><strong>Name:</strong> ${fullName}</p>
      <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
      <p><strong>Phone:</strong> ${phone}</p>
      ${residence ? `<p><strong>Residence:</strong> ${residence}</p>` : ""}
      ${departureDate ? `<p><strong>Departure:</strong> ${new Date(departureDate).toLocaleDateString()}</p>` : ""}
      ${returnDate ? `<p><strong>Return:</strong> ${new Date(returnDate).toLocaleDateString()}</p>` : ""}
      <p><strong>Travelers:</strong> ${travelers}</p>
      ${budget ? `<p><strong>Budget:</strong> ${budget}</p>` : ""}
      ${products.length ? `<p><strong>Selected Products/Programs:</strong><ul>${products.map((p:any) => `<li>${p.name}${p.price ? ` ($${p.price})` : ''}</li>`).join('')}</ul></p>` : ""}
      ${comments ? `<p><strong>Comments:</strong> ${comments.replace(/\n/g, "<br/>")}</p>` : ""}
      <p style=\"color:#888;font-size:12px;\">This email was generated by the website. <br/>To reply to the client, simply reply to this email or click the email address above.</p>
    `
  await sendMail({ to: adminEmails, subject: `Booking request from ${fullName}`, html })

    // Confirmation email to customer (use production app URL)
    const appUrl = process.env.NEXT_PUBLIC_APP_URL_PROD || "https://main-gihomart.vercel.app";
    const confirmHtml = `
      <h2>Thanks for your booking request</h2>
      <p>Hi ${fullName},</p>
      <p>We received your booking request and will contact you shortly.</p>
      ${residence ? `<p><strong>Residence:</strong> ${residence}</p>` : ""}
      ${departureDate ? `<p><strong>Departure:</strong> ${new Date(departureDate).toLocaleDateString()}</p>` : ""}
      ${returnDate ? `<p><strong>Return:</strong> ${new Date(returnDate).toLocaleDateString()}</p>` : ""}
      <p><strong>Travelers:</strong> ${travelers}</p>
      ${comments ? `<p><strong>Comments:</strong> ${comments.replace(/\n/g, "<br/>")}</p>` : ""}
      <p style=\"color:#888;font-size:12px;\">This is a confirmation of your submission.<br/>Visit our website: <a href='${appUrl}'>${appUrl}</a></p>
    `
    await sendMail({ to: email, subject: "We received your booking request", html: confirmHtml })

    return res.status(201).json({ success: true })
  } catch (error) {
    return res.status(500).json({ error: "Failed to submit booking" })
  }
}
